# Generated by Django 2.0.2 on 2018-02-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spinge', '0003_auto_20180215_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_professor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
